name: Build (Rust → WASM)

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

concurrency:
  group: build-${GITHUB_REF}
  cancel-in-progress: true

jobs:
  rust-wasm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust + wasm32 target
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            agent/host

      - name: Build host as WASM
        working-directory: agent/host
        run: cargo build --release --target wasm32-unknown-unknown

      - name: Upload wasm artifact
        uses: actions/upload-artifact@v4
        with:
          name: agent_wasm
          path: agent/host/target/wasm32-unknown-unknown/release/*.wasm
