name: build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false   # pastikan tidak memproses submodule

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}

      - name: Build workspace
        run: cargo build --workspace --verbose

      - name: Build WASM (agent-template)
        run: cargo build -p agent-template --target wasm32-unknown-unknown --release --verbose

      - name: Upload WASM artifact
        uses: actions/upload-artifact@v4
        with:
          name: agent-template.wasm
          path: target/wasm32-unknown-unknown/release/agent_template.wasm
