name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Build workspace
        run: cargo build --workspace --verbose

      - name: Build WASM (auto-detect cdylib crates)
        shell: bash
        run: |
          set -e
          rustup target add wasm32-unknown-unknown
          found=0
          while IFS= read -r manifest; do
            if grep -q "^\[lib\]" "$manifest" && grep -iq "crate-type.*cdylib" "$manifest"; then
              pkg=$(grep -m1 '^name[[:space:]]*=' "$manifest" | sed -E 's/.*name[[:space:]]*=[[:space:]]*"([^"]+)".*/\1/')
              [ -z "$pkg" ] && pkg=$(basename "$(dirname "$manifest")")
              echo "==> Building $pkg (WASM)"
              cargo build -p "$pkg" --target wasm32-unknown-unknown --release
              found=1
            fi
          done < <(find . -name Cargo.toml)
          [ "$found" = 0 ] && echo "No cdylib crates found; skipping."
