name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Build workspace
        run: cargo build --workspace --verbose

      - name: Build WASM (auto detect cdylib crates)
        run: |
          rustup target add wasm32-unknown-unknown
          while IFS= read -r manifest; do
            if grep -q "crate-type.*cdylib" "$manifest"; then
              pkg=$(grep -m1 '^name' "$manifest" | sed -E 's/.*"([^"]+)".*/\1/')
              echo "==> Building $pkg (WASM)"
              cargo build -p "$pkg" --target wasm32-unknown-unknown --release
            fi
          done < <(find . -name Cargo.toml)
